### ISSUE TITLE
git checkout on commit-hash fails

### ISSUE THREAD

**Issue by WanzenBug** [coduno/toolbox#3]
post-receive hook fails to checkout the supplied hash.
Apparently "." is not a git repository

**Comment by lorenzleutgeb** [comment]
For future reference: This was [fixed](https://github.com/coduno/engine/commit/b3c056ce319a5ddfc46b3403414362e4bcf653e8#diff-a86ae245bf6143bb1ca58515df238f88R6) in b3c056ce319a5ddfc46b3403414362e4bcf653e8.

The issue was that `$GIT_DIR` is set by Git when executing a hook, that always repointed the calls to Git inside the hook to the original repo, which is quite confusing.
